### ISSUE TITLE
Forward reference name is not defined error when static type checking with mypy

### ISSUE THREAD

**Issue by peterroelants** [google/jaxtyping#29]
Because strings in types are typically interpreted as forward references I'm getting `Name "*" is not defined` errors using mypy.

I know from the [documentation](https://github.com/google/jaxtyping/blob/main/FAQ.md#flake8-is-throwing-an-error) that to deal with similar issues related to flake8 checks it to prepend a space, and ignore F722.

For example:
```python
def test_error() -> Float[Array, " x"]:
    ...
```
Is resulting in: `error: Name "x" is not defined`. 

Are there any recommendations to avoid thise forward reference errors when static type checking?

I'm using:
- Python 3.10
- mypy 0.971
- jax 0.3.17
- jaxtyping 0.2.4

**Comment by peterroelants** [comment]
Now what seems to work is just declaring the variable somewhere in the file, e.g.:
```python
_x = ...

def test_error() -> Float[Array, "_x"]:
    ...
```
Seems to avoid any issues, and also the flake8 ignoring of F722 is not needed anymore.

**Comment by patrick-kidger** [comment]
Okay, I think this should be fixed as of version 0.2.5. My MWE was:
```python
from jaxtyping import Array, Float                                                                                                                                  
                                                                                                                                                                    
def test_error() -> Float[Array, "x"]:                                                                                                                              
    ...
```

Can you confirm this?

(FWIW the issue was just a build one -- the `py.typed` file just wasn't being distributed.)

**Comment by peterroelants** [comment]
> Can you confirm if things work for you after updating? (You may need to delete `.mypy_cache`.)

This seems to work, thanks :+1: . However, I still have append spaces to avoid flake8 from complaining.
